### ISSUE TITLE
add username to the log table

### ISSUE THREAD

**Issue by omidMolaverdi** [yadahan/laravel-authentication-log#20]
Thanks for the great work.

I realised that if the user cancels its account then the log table will only keep the user_id that is not very informative. Is there any way to add the username to the table?

**Comment by omidMolaverdi** [comment]
Hi, 

is there any update on this q question please?

**Comment by TechTailor** [comment]
I suppose the workaround would be to soft-delete the user model instead of fully deleting it from the db (can delete related data if a gdpr request is filed) but in my personal opinion you should never remove the user id/email from the db but rather disable the login for it (this way you always have a record of whether the user/email was used before).

-TT

**Comment by omidMolaverdi** [comment]
Thanks for the reply.
Soft deleting sounds not a good idea to me as first I find it quite unfair to the user who requested a DELETE :) and secondly, I have to neutralise the user information such as email, logins, IP etc otherwise, it cannot sign up with the same credentials.  I also find it unfair to remove all user information but the username (and stats such as IP, browser etc) but I find it less cheaty than soft deleting user info. :)

**Comment by TechTailor** [comment]
Hey,

If we are talking about fairness for users, then when the user requests account deletion you should purge absolutely every record of that user from your db (including logs) otherwise why would you not soft-delete/disable login. Sure you can remove any sensitive data (like credit-card/bank details etc) but removing everything (to allow re-signup with same email address) but still storing username & IP doesnt make sense to me. 

If you can provide a use-case where doing such a thing makes sense, I would be more than happy to change my opinion on this but until then you should either just disable login on account delete or purge everything of the user.

-TT

**Comment by omidMolaverdi** [comment]
That makes sense to me. The problem is the cyber regulations in some countries. Based on local laws, I should keep the activities for 6 months, otherwise, I would be more than happy to purge immediately after the user requests a delete.

**Comment by TechTailor** [comment]
Correct me if I am wrong but doesnt the GDPR and similar laws require you to remove all related info of the user if requested (or atleast thats how I have interpreted it). But if not and as you mentioned the regulations for retaining, the best way is to disable login (cause just storing a username without email/name/address for legal reasons is pointless) and if need be send a notification to the user mentioning a complete purge after x months (to comply with local laws, etc). 

-TT
