### ISSUE TITLE
Dont delete logs base on config


### ISSUE THREAD

**Issue by lloricode** [yadahan/laravel-authentication-log#47]
Hi, can i made a pr for disable delete logs on commands, in case of running it, it will throw exception or warning that clearing log is not allowed,

because we need the logs for generating time in ang time out

i like to pr to config file, set false to disable clearing logs

or any idea what is best?

**Comment by TechTailor** [comment]
Hey, 

There seems to be some confusion, let me clear it for you. The package itself cannot clear the old logs, in order to remove/delete old logs (as configured in the config file), you need to manually run the `php artisan authentication-log:clear` command in the console or schedule the same using cron jobs. 

As long as you don't run/schedule it yourself, the authentication logs will be persisted until you purge your db. Adding any additional option to the config file is pointless. If you require a dynamic option, you can add one yourself in your scheduler.

-TT

**Comment by lloricode** [comment]
you have a point, thanks
